name = "BetaCraft"
author = "Sam302rk, Mariology"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "236e3f6ece5d68cc98fa2fb3f64b06ce520ed8530634c1d5a35f565d08a5ae18"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21.1"]
