name = "Mario Pack"
author = "Sam302rk, Mariology"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a4562400635bf37377c3386f73bf7f3c92dec51f01e67c85843f9a1216ac988f"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
