name = "Mario Pack"
author = "Sam302rk, Mariology"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "64d75ea3ade79546f4ce8007183838821474ba17d76d0a91f3d62c96e5537c66"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
