name = "Mario Pack"
author = "Sam302rk, Mariology"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ea2a7251f3beced4045d5c29cda7ca38f0ae88a69703f0ff532f24fc93fe7ea"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
