name = "BetaCraft"
author = "Sam302rk, Mariology"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f0213ba75317083edc603b049c06df0fb8f7baf4dc14bbb916d792bb0c8f97c6"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
