name = "Mario Pack"
author = "Sam302rk, Mariology"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c88631556de2524da393f69018b543354f18d562110131bcc1c8d7ac64481f9f"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
