name = "BetaCraft"
author = "Sam302rk, Mariology"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "90ce326a029f849a3194cbed0aad68afce82f68535a769ecbca82bcd79ae845f"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
