name = "Mario Pack"
author = "Sam302rk, Mariology"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5da84fc22c91d26ec590e79bcd67633073458c1554fe759a6f6187a47563982f"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
