name = "Mario Pack"
author = "Sam302rk, Mariology"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2d06fbefbd6304bb4efa8d662d130eee5222350651b0a7090d0c1155410a4459"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
