name = "BetaCraft"
author = "Sam302rk, Mariology"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e8eb6256c6c53e11fca5075f54851b29e3d9392cc4d54b15658fca2d4f7d105a"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
