name = "Mario Pack"
author = "Sam302rk, Mariology"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8172a249d20ecdbd999302e7c91ff99cbf3d961a39bb5f27d86431ce5b7c34f3"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
