name = "BetaCraft"
author = "Sam302rk, Mariology"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e2b1a6105ddb3da22fd4015dcae1c0b03e8b3981bcec430703df5ab59249e70b"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
